travis:
  secure:
    BINSTAR_TOKEN: ZK3AdMveSzT3+lEy5DynjhBwZZXgYeQSGbFX/xaZvN+geoBH9DgqpiyCBvq8teETuIzI/WLQClb63kyUQBMJi0VP0LjzyZLjALH1YmU8GYDJCRmc4mg5XoJWuYPCAudgPR+aS9ZstWMjb7qcoWsezVr0ze0dvdfox+GwryuC6Wuqcp/3fZI/+0qFc7xXta1uI6j4Qvd4js2kGJyJEB8ayq+xi30wByMchXFn0HrLrr/O4ORVPFKyViaPt6qSPyqlMmucMHlgYmqmAB1/RxFAIDI+IwDJLSOayNICGERtyZpnoVqSragdcUVTofebC7CiwzqUkXt+JMDdnfck0efautlQB6/e3kn4Cq/2CuW00qyy/AnOsja1NUZrA5aKIQwp9x6ljiZFqfiDDr0CRNzfeYemijPinlqY1kH0d4VgqD1TY2nNQJtu2hpqVIKSsf6NdeLFOielSsl/ZtmTX09Par/1UAtFnyEpC1kyrTeQpAalrM1zYY/9FLy1hoSmcPzqL6euzfLyrjzQaxP9v+jD74CoxnuXAk2byEikp8IjjNVap7SafRgKmHMr1ABoR3qIUNzi6dm1Lvw8hvdW75ldnDgD7IODb9hzs80A72sRr6LblnJS1vP977N0Jk1s/CxnpimwdNPFndzbljFlKBb0/C8KrVbvZ6hHmY/B1yQm+9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
